use_modular_headers!

# # Resolve react_native_pods.rb with node to allow for hoisting
# require Pod::Executable.execute_command('node', ['-p',
#   'require.resolve(
#     "react-native/scripts/react_native_pods.rb",
#     {paths: [process.argv[1]]},
#   )', __dir__]).strip

# # platform :ios, min_ios_version_supported
# platform :ios, '13.4'
# prepare_react_native_project!

# # If you are using a `react-native-flipper` your iOS build will fail when `NO_FLIPPER=1` is set.
# # because `react-native-flipper` depends on (FlipperKit,...) that will be excluded
# #
# # To fix this you can also exclude `react-native-flipper` using a `react-native.config.js`
# # ```js
# # module.exports = {
# #   dependencies: {
# #     ...(process.env.NO_FLIPPER ? { 'react-native-flipper': { platforms: { ios: null } } } : {}),
# # ```
# flipper_config = ENV['NO_FLIPPER'] == "1" ? FlipperConfiguration.disabled : FlipperConfiguration.enabled

# linkage = ENV['USE_FRAMEWORKS']
# if linkage != nil
#   Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
#   use_frameworks! :linkage => linkage.to_sym
# end

# target 'flanningapp' do
#   config = use_native_modules!

#   pod 'Firebase/Core', :modular_headers => true
#   pod 'Firebase/Auth', :modular_headers => true
#   pod 'Firebase/Firestore', :modular_headers => true
#   pod 'Firebase/Database', :modular_headers => true

#   # pod 'gRPC-C++', '1.43.0'
#   # pod 'gRPC-Core', '1.43.0'

#   use_react_native!(
#     :path => config[:reactNativePath],
#     # Enables Flipper.
#     #
#     # Note that if you have use_frameworks! enabled, Flipper will not work and
#     # you should disable the next line.
#     :flipper_configuration => flipper_config,
#     # An absolute path to your application root.
#     :app_path => "#{Pod::Config.instance.installation_root}/.."
#   )

#   target 'flanningappTests' do
#     inherit! :complete
#     # Pods for testing
#   end

#   post_install do |installer|
#     # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
#     react_native_post_install(
#       installer,
#       config[:reactNativePath],
#       :mac_catalyst_enabled => false
#     )

#     installer.pods_project.targets.each do |target|
#       target.build_configurations.each do |config|
#         config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.4'
#         config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'arm64'
#         config.build_settings['ARCHS'] = '$(ARCHS_STANDARD)'
#       end
#     end
#   end
# end


# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, min_ios_version_supported
prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'flanningapp' do
  config = use_native_modules!
  use_frameworks! :linkage => :static

  # use_frameworks!
  # pod 'Firebase/Core'
  # pod 'Firebase/Auth'
  # pod 'Firebase/Firestore'
  # pod 'Firebase/Database'
  # pod 'gRPC-C++', :modular_headers => false
  # pod 'gRPC-Core', :modular_headers => false

  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  target 'flanningappTests' do
    inherit! :complete
    # Pods for testing
  end

  post_install do |installer|
    # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      # :ccache_enabled => true
    )
  
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        # config.build_settings['ARCHS'] = '$(ARCHS_STANDARD)'
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.4'
        # config.build_settings['EXCLUDED_ARCHS'] = 'arm64'
      end
    end
  end
end
